<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>AgroAide administration</title>@vite(['resources/css/app.css', 'resources/js/app.js'])</head>
<body class="bg-stone-100 text-stone-900"><main class="mx-auto max-w-6xl space-y-6 px-4 py-8">
<div class="flex justify-between"><a href="{{ route('staff.dashboard') }}" class="text-emerald-700 underline">Back to operations</a><a href="{{ route('staff.audit') }}" class="text-emerald-700 underline">Audit details</a></div>
@if(session('status'))<p class="rounded bg-emerald-100 p-3">{{ session('status') }}</p>@endif
<section class="rounded-xl border bg-white p-6"><h1 class="text-2xl font-bold">Administration</h1><p class="mt-2 text-sm text-stone-600">This page contains staff account details and is restricted to administrators.</p></section>
<section class="rounded-xl border bg-white p-6"><h2 class="font-bold">Confidence-policy versions</h2><form method="post" action="{{ route('staff.policies.store') }}" class="mt-4 grid gap-3 sm:grid-cols-5">@csrf<input name="name" required placeholder="Policy name" class="rounded border p-2"><input name="version" required placeholder="Version" class="rounded border p-2"><input name="retake_below" value="0.60" readonly class="rounded border bg-stone-100 p-2"><input name="review_below" value="0.85" readonly class="rounded border bg-stone-100 p-2"><input type="hidden" name="require_canonical" value="1"><button class="rounded bg-emerald-700 px-3 py-2 text-white">Create version</button></form>
<div class="mt-4">@foreach($policies as $policy)<div class="flex items-center justify-between border-t py-2"><span>{{ $policy->name }} v{{ $policy->version }} · &lt;{{ $policy->retake_below }} retake · &lt;{{ $policy->review_below }} review · {{ $policy->active ? 'active' : 'inactive' }}</span>@unless($policy->active)<form method="post" action="{{ route('staff.policies.activate', $policy) }}">@csrf<button class="rounded border px-3 py-1 text-sm">Activate</button></form>@endunless</div>@endforeach</div></section>
<section class="rounded-xl border bg-white p-6"><h2 class="font-bold">Staff role assignment</h2><div class="mt-4 overflow-x-auto"><table class="w-full text-left text-sm"><thead><tr><th>Name</th><th>Email</th><th>Current role</th><th>Assign</th></tr></thead><tbody>@foreach($users as $user)<tr class="border-t"><td class="py-2">{{ $user->name }}</td><td>{{ $user->email }}</td><td>{{ $user->role }}</td><td><form method="post" action="{{ route('staff.users.role', $user) }}" class="flex gap-2">@csrf @method('PATCH')<select name="role" class="rounded border p-1">@foreach(['farmer','agronomist','admin'] as $role)<option value="{{ $role }}" @selected($user->role === $role)>{{ $role }}</option>@endforeach</select><button class="rounded border px-2">Save</button></form></td></tr>@endforeach</tbody></table></div>{{ $users->links() }}</section>
<section class="rounded-xl border bg-white p-6"><h2 class="font-bold">Evaluation datasets</h2><p class="mt-2 text-sm">Private files are imported only with <code>agroaide:evaluation:import</code>; see <code>docs/dataset-protocol.md</code>. Queue runs from a locked dataset detail page.</p>@foreach($datasets as $dataset)<p class="mt-2 border-t pt-2"><a class="text-emerald-700 underline" href="{{ route('staff.evaluations.datasets.show', $dataset) }}">{{ $dataset->name }} v{{ $dataset->version }}</a> · {{ $dataset->items_count }} items · {{ $dataset->locked_at ? 'locked' : 'not ready' }}</p>@endforeach</section>
</main></body></html>
