<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Evaluation run #{{ $run->id }}</title>@vite(['resources/css/app.css', 'resources/js/app.js'])</head>
<body class="bg-stone-100 text-stone-900"><main class="mx-auto max-w-6xl space-y-6 px-4 py-8">
<a href="{{ route('staff.dashboard') }}" class="text-emerald-700 underline">Back to operations</a>
@php($summary = $run->metrics ?? [])
<section class="rounded-xl border bg-white p-6"><h1 class="text-2xl font-bold">Evaluation run #{{ $run->id }}</h1><p class="mt-2">{{ $run->status }} · {{ $run->sample_count }} samples · model {{ $run->model_version_id }} · prompt {{ $run->prompt_version_id }} · policy {{ $run->confidence_policy_id }}</p>
<div class="mt-5 grid gap-3 sm:grid-cols-3"><div class="rounded bg-stone-50 p-3">Accuracy: {{ data_get($summary, 'accuracy') === null ? 'Not measured' : number_format(data_get($summary, 'accuracy') * 100, 1).'%' }}</div><div class="rounded bg-stone-50 p-3">Coverage: {{ data_get($summary, 'coverage') === null ? 'Not measured' : number_format(data_get($summary, 'coverage') * 100, 1).'%' }}</div><div class="rounded bg-stone-50 p-3">P95 latency: {{ data_get($summary, 'latency.p95_ms') === null ? 'Not measured' : number_format(data_get($summary, 'latency.p95_ms')).' ms' }}</div></div></section>
<section class="overflow-x-auto rounded-xl border bg-white p-6"><h2 class="mb-3 font-bold">Per-class metrics</h2><table class="w-full text-left text-sm"><thead><tr><th>Class</th><th>TP</th><th>FP</th><th>FN</th><th>TN</th><th>Precision</th><th>Recall</th><th>F1</th><th>FPR</th></tr></thead><tbody>@foreach($metrics as $metric)<tr class="border-t"><td class="py-2">{{ $metric->label_name }}</td><td>{{ $metric->tp }}</td><td>{{ $metric->fp }}</td><td>{{ $metric->fn }}</td><td>{{ $metric->tn }}</td><td>{{ $metric->precision === null ? 'n/a' : number_format($metric->precision, 3) }}</td><td>{{ $metric->recall === null ? 'n/a' : number_format($metric->recall, 3) }}</td><td>{{ $metric->f1 === null ? 'n/a' : number_format($metric->f1, 3) }}</td><td>{{ $metric->fpr === null ? 'n/a' : number_format($metric->fpr, 3) }}</td></tr>@endforeach</tbody></table></section>
</main></body></html>
